/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

	docs: [
		"introduction",
		{
			type: "category",
			label: "Getting started",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "getting-started",
				},
			// 	'installation',
			// 	'configuration',
			// 	'playground',
			// 	'typescript-support',
			],
		},
		{
			type: "category",
			label: "Providers",
			link: {
				type: "generated-index",
			},
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "providers",
				},
			]
		},
		{
			type: "category",
			label: "Components",
			link: {
				type: "generated-index",
			},
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "components",
				},
			]
		},
		//senders: []
		{
			type: "category",
			label: "Guides",
			link: {
				type: "generated-index",
			},
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "guides",
				},
			]
		},
		"external",
		"changelog",
		"contributing",
	],

	api: [

	],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
