/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

	docs: [
		"introduction",
		{
			label: "Getting started",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "getting-started",
				},
			],
		},
		{
			label: "Guides",
			type: "category",
			link: {
				type: "doc",
				id: "guides/guides",
				//type: "generated-index",
			},
			collapsed: true,
			items: [
				{
					type: "autogenerated",
					dirName: "guides",
				},
			]
		},
		{
			label: "Packages",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "packages",
				},
			]
		},
		"external",
		"changelog",
		"contributing",
	],

	api: [
		{
			label: "Providers",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/providers",
				},
			],
		},
		"api/uploader",
		"api/context",
		{
			label: "Components",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/components",
				},
			],
		},
		{
			label: "Hooks",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/hooks",
				},
			],
		},
		{
			label: "HOCs",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/hocs",
				},
			],
		},
		{
			label: "Enhancers",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/enhancers",
				},
			],
		},
		{
			label: "Senders",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/senders",
				},
			],
		},
		{
			label: "Utilities",
			type: "category",
			link: {
				type: "generated-index",
			},
			collapsed: false,
			items: [
				{
					type: "autogenerated",
					dirName: "api/utils",
				},
			],
		},
		"api/constants",
		"api/entities",
		"api/events",
		"api/types",
	],
};

module.exports = sidebars;
